name : Tag Workflow

on :
  push:
    tags:
      - 'v*'


jobs:
  job1:
    value : VAR1 = 'test'
    runs-on : ubuntu-latest
    steps:
      - name: VAR1
        run: echo VAR1
    condition : if {job1 = not true}
      job2:
        needs: job1
        runs-on : ubuntu-latest
        steps:
          - name: Step 2
            run: echo "Le job précédent a échoué"


#Bonus partie : retirer la condition pour qu'elle s'execute quelque soit le résultat du job précédent :

name : Tag Workflow

on :
  push:
    tags:
      - 'v*'


jobs:
  job1:
    value : VAR1 = 'test'
    runs-on : ubuntu-latest
    steps:
      - name: VAR1
        run: echo VAR1
  job2:
    needs: job1
    runs-on : ubuntu-latest
    steps:
      - name: Step 2
        run: echo "Le job précédent a échoué"
