name: Tag Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: VAR1
        run: echo 'VAR1 = "test"'

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: failure()  # Exécute job2 seulement si job1 échoue
    steps:
      - name: Step 2
        run: echo "Le job précédent a échoué"
